name: Push File

on: 
 workflow_dispatch: {}
 push:
  branches: 
   - main
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Pushes test folder
      uses: GuillaumeFalourd/copy-push-files@v1
      with:
          email: sravani14injarapu@gmail.com
          name: ${{ github.actor }}
          commit_message: your_message
          target_branch: main
          source_files: ./docker-compose.txt
          remote_repository: https://github.com/sravani1714/sravani
          access_token: ${{ secrets.ACTIONS_KEY }}
		  

