name: workflow_02
on:
  repository_dispatch:
    types: [sample_push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTIONS_KEY }}
        with:
          source-files: './static'
          destination-username: 'sravani1714'
          destination-repository: 'sravani'
          destination-directory: 'sravani/static/'
          commit-email: 'sravani14injarapu@gmail.com'
